name: airsense
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  dio: ^5.2.1+1
  envied: ^0.3.0+3
  riverpod_generator: ^2.2.3
  toggle_switch: ^2.1.0
  fl_chart: ^0.63.0
  go_router: ^9.0.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  freezed: ^2.3.5
  envied_generator: ^0.3.0+3

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/launcher_icon.png'
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#090912"
  adaptive_icon_foreground: 'assets/icon/launcher_icon.png'

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch